---
- name: Install python3 
  hosts: all
  become: yes
  tasks:
    - name: make sure  python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: Install docker-compose
  hosts: all
  become: yes
  tasks:
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      dest: /usr/local/bin/docker-compose
      mode: +x 

- name: Start docker and user to docker group
  hosts: all
  become: yes
  vars_files:
  - project-vars
  tasks:
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

    - name: Create new linux user
      user: marv
      groups: "{{user_groups}}"


- name: Start docker containers
  hosts: all
  become: yes
  become_user: marv
  vars_files:
  - project-vars
 
  tasks:
    - name: Copy docker compose
      copy:
        src: /home/marv/Desktop/ansible/docker-compose.yaml
        dest: /home/marv/docker-compose.yaml

    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: marv254
        password: "{{docker_password}}"
    
    - name: Start containers from docker compose
      docker_compose:
        project_src: /home/marv
