---
- name: Install java and net-tools
  hosts: nexus
  become: true
  tasks:
    - name: Update yum repo and cache
      yum : update_cache=yes 
    - name: Install Java 8
      yum : name=java-1.8.0-openjdk
    - name: Install net-tools
      yum : name=net-tools

- name: Download and unpack nexus
  hosts: nexus
  become: true
  tasks:
    - name: Create opt directory if does not exist
      file:
        path: /opt
        state: directory
    - name: Download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: Untar nexus install
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes