---
- name: Install python3 
  hosts: docker_server
  become: yes
  tasks:
    - name: make sure  python3 and docker are installef
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present

- name: Install docker-compose
  hosts: docker_server
  become: yes
  tasks:
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      dest: /usr/local/bin/docker-compose
      mode: +x 

- name: Start docker and user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes 
    - name: Reconnect to server session
      meta: reset_connection

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: Pull redis
      command: docker pull redis