---
- name: Install python3 
  hosts: tag_Name_dev_server
  become: yes
  tasks:
    - name: make sure  python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: Install docker-compose
  hosts: tag_Name_dev_server
  become: yes
  tasks:
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      dest: /usr/local/bin/docker-compose
      mode: +x 

- name: Start docker 
  hosts: tag_Name_dev_server
  become: yes
 
  tasks:
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
  
- name: Start docker 
  hosts: tag_Name_dev_server
  become: yes
  vars_files:
    - project-vars
  roles:
    - create_user
  


- name: Start docker containers
  hosts: tag_Name_dev_server
  become: yes
  become_user: marv
  vars_files:
    - project-vars
  roles:
    - start_containers
    
