---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: absent
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: ~/Desktop/ansible/nginx-deployment.yaml
        state: absent
        namespace: my-app