- name: Copy docker compose
  copy:
    src: docker-compose.yaml
    dest: /home/marv/docker-compose.yaml

- name: Docker login
  docker_login:
    registry_url: https://index.docker.io/v1
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    
- name: Start containers from docker compose
  docker_compose:
    project_src: /home/marv